<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Tarea 1: Eigenvectores y Eigenvalores</font>
___

Esta tarea consiste en calcular eigenvalores y eigenvectores de matrices siguiendo el calculo a mano, usando la librería numpy y sympy.

Los eigenvalores y eigenvectores son conceptos fundamentales en álgebra lineal y tienen aplicaciones en machine learning, física, ingeniería y más.

In [4]:
import numpy as np

**1. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$A = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}$$

In [5]:
A = np.array([[4, 2],
              [1, 3]])
eigvals_A, eigvecs_A = np.linalg.eig(A)
print("1. Matriz A:")
print("Eigenvalores:", eigvals_A)
print("Eigenvectores:\n", eigvecs_A)
print("\n")

1. Matriz A:
Eigenvalores: [5. 2.]
Eigenvectores:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]




**2. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$B = \begin{bmatrix} 2 & 0 \\ 0 & 5 \end{bmatrix}$$

In [6]:
B = np.array([[2, 0],
              [0, 5]])
eigvals_B, eigvecs_B = np.linalg.eig(B)
print("2. Matriz B:")
print("Eigenvalores:", eigvals_B)
print("Eigenvectores:\n", eigvecs_B)
print("\n")

2. Matriz B:
Eigenvalores: [2. 5.]
Eigenvectores:
 [[1. 0.]
 [0. 1.]]




**3. Eigenvalores y eigenvectores de una matriz 3x3**

Calcula los eigenvalores y eigenvectores de la siguiente matriz:

$$C = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix}$$

In [7]:
C = np.array([[1, 2, 3],
              [0, 4, 5],
              [0, 0, 6]])
eigvals_C, eigvecs_C = np.linalg.eig(C)
print("3. Matriz C:")
print("Eigenvalores:", eigvals_C)
print("Eigenvectores:\n", eigvecs_C)
print("\n")

3. Matriz C:
Eigenvalores: [1. 4. 6.]
Eigenvectores:
 [[1.         0.5547002  0.51084069]
 [0.         0.83205029 0.79818857]
 [0.         0.         0.31927543]]




**4. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$D = \begin{bmatrix} 0 & 1 \\ -2 & -3 \end{bmatrix}$$

In [8]:
D = np.array([[0, 1],
              [-2, -3]])
eigvals_D, eigvecs_D = np.linalg.eig(D)
print("4. Matriz D:")
print("Eigenvalores:", eigvals_D)
print("Eigenvectores:\n", eigvecs_D)
print("\n")

4. Matriz D:
Eigenvalores: [-1. -2.]
Eigenvectores:
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]




**5. Crea una matriz cuadrada aleatoria de tamaño 4x4 y calcula sus eigenvalores y eigenvectores.**

In [9]:
np.random.seed(0)  # Para reproducibilidad
E = np.random.rand(4,4)
eigvals_E, eigvecs_E = np.linalg.eig(E)
print("5. Matriz aleatoria 4x4:")
print("Matriz:\n", E)
print("Eigenvalores:", eigvals_E)
print("Eigenvectores:\n", eigvecs_E)

5. Matriz aleatoria 4x4:
Matriz:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]
Eigenvalores: [ 2.28158836 -0.5139378  -0.22422772  0.53013911]
Eigenvectores:
 [[ 0.52354106 -0.10090767  0.5285094  -0.1584302 ]
 [ 0.49196427  0.55773542 -0.43250014  0.36386336]
 [ 0.59384504  0.23102177 -0.57357157 -0.81262442]
 [ 0.36224851 -0.79080831  0.45236832  0.42678435]]
